{% set version = "1.6-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vars
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vars_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vars/vars_{{ version }}.tar.gz
  sha256: 9b3df03232fbedd30a89af10b20b540fce20ddd36602853857d47242d66f14c5

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-lmtest >=0.9_26
    - r-sandwich >=2.2_4
    - r-strucchange
    - r-urca >=1.1_6
  run:
    - r-base
    - r-mass
    - r-lmtest >=0.9_26
    - r-sandwich >=2.2_4
    - r-strucchange
    - r-urca >=1.1_6

test:
  commands:
    - $R -e "library('vars')"           # [not win]
    - "\"%R%\" -e \"library('vars')\""  # [win]

about:
  home: http://www.pfaffikus.de
  license: GPL-2.0-or-later
  summary: Estimation, lag selection, diagnostic testing, forecasting, causality analysis, forecast error variance decomposition and impulse response functions of VAR models and estimation of SVAR and SVEC models.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
