# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VroZM+W6m3R0Epn9q2lqbu0oFbWQ2QK0hWzFurf3B9de5Wqnk2NBx1EgSIBNjY2m7d+eP21WsP3qK31LsnpsaIWEutGTVcLIhAJmTrBRWs7+r17+/JMQO5J+tXjG8gufqW1naM5vZiA4Y4xpUaV/sb4tqIVvQ/My5lzBo7bE2ns7/GgnPBp/LoMqhR/weS+pa5I/chtlK1rtQ+KjGpKnTXvWjzMc6c0hZ4Av+hFyxFSwBG2VWPfcDmavr003ftL6rBHPzb6xdPceNjoJmplfq1FeHHBeK02UnVZ4FKGkMLJkZ2Zr5Um+dCOkm6m4kod4Megxc2+d9C0/0IPUAyijkGk1zz/TU0TXWO17KMW7jj7kJe3KSJG7utWL9440YuRZNvPQTINEjwXtd2kptLlyi5rAX83Ip4dd5VqZmp7SlcL6WIXXom0BcLHj8HagaDkiNq6/HgFScFR+txzWWwr2D3VZ6snUQpwtJv5Oj6Ob99tIqh41DrzI7ZGMf6HuGqjjS490pnYIMn+J+GR3WCrO+PqRLI7qbdP1jw/FSRn1wBcyLpx4lsw2wmQhPXYmHH/juAkdCYtI4+esOV6r4ph2hiX5HW5XOiYNet6LDlA4wLkU7w76KeskywtERrjUSjYPoV56fBFHJTEvYAm1VrfwelWA0MXpVKnt/rT+ZvvcuQc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
