travis:
  secure:
    BINSTAR_TOKEN: VroZM+W6m3R0Epn9q2lqbu0oFbWQ2QK0hWzFurf3B9de5Wqnk2NBx1EgSIBNjY2m7d+eP21WsP3qK31LsnpsaIWEutGTVcLIhAJmTrBRWs7+r17+/JMQO5J+tXjG8gufqW1naM5vZiA4Y4xpUaV/sb4tqIVvQ/My5lzBo7bE2ns7/GgnPBp/LoMqhR/weS+pa5I/chtlK1rtQ+KjGpKnTXvWjzMc6c0hZ4Av+hFyxFSwBG2VWPfcDmavr003ftL6rBHPzb6xdPceNjoJmplfq1FeHHBeK02UnVZ4FKGkMLJkZ2Zr5Um+dCOkm6m4kod4Megxc2+d9C0/0IPUAyijkGk1zz/TU0TXWO17KMW7jj7kJe3KSJG7utWL9440YuRZNvPQTINEjwXtd2kptLlyi5rAX83Ip4dd5VqZmp7SlcL6WIXXom0BcLHj8HagaDkiNq6/HgFScFR+txzWWwr2D3VZ6snUQpwtJv5Oj6Ob99tIqh41DrzI7ZGMf6HuGqjjS490pnYIMn+J+GR3WCrO+PqRLI7qbdP1jw/FSRn1wBcyLpx4lsw2wmQhPXYmHH/juAkdCYtI4+esOV6r4ph2hiX5HW5XOiYNet6LDlA4wLkU7w76KeskywtERrjUSjYPoV56fBFHJTEvYAm1VrfwelWA0MXpVKnt/rT+ZvvcuQc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
